### ISSUE TITLE
Unable to import module 'lambda-fortune'

### ISSUE THREAD

**Issue by keplersj** [anandanand84/aws-lambda-tensorflow-dependencies#1]
I'm attempting to use this module to upload a function, but when it is run I'm getting an error back `Unable to import module 'lambda-fortune'`

**Comment by anandanand84** [comment]
Can you try using this module https://github.com/anandanand84/aws-lambda-tensorflow This repo is just files to be used in the above mentioned repo

**Comment by keplersj** [comment]
Sorry, I'm being more unclear than I'd like. I am using that module to upload TensorFlow project, but when Lambda executes the uploaded code it gives back the error I posted above. I reported the issue here because it seems that the zip file does not have a Python module needed for TensorFlow to function properly.

**Comment by verveguy** [comment]
If the problem is indeed that you need a newer build of tensorflow, you can try to do so yourself with the instruction here:

https://github.com/anandanand84/aws-lambda-tensorflow/blob/master/Creating-Dependency.md

However, I've also opened a general issue in the primary project requesting image rebuilds for tensorflow 0.11.0

https://github.com/anandanand84/aws-lambda-tensorflow/issues/1

**Comment by keplersj** [comment]
I'm going to go ahead and close this. I'm not actively working on the project that depended on this anymore, and it's very likely my issue was on my own error.
